# Generated by Django 3.2 on 2024-04-04 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0002_alter_extenduser_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='extenduser',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
