# Generated by Django 3.2 on 2024-04-04 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0003_extenduser_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extenduser',
            name='is_verified',
        ),
    ]
